In [1]:
import networkx as nx
import numpy as np

In [ ]:
# forward disruption


# backward disruption
BR = 

In [11]:
n_nodes = 20

In [31]:
g = nx.erdos_renyi_graph(n_nodes, 0.3)

In [59]:
adj_mat = nx.adjacency_matrix(g).toarray().astype(bool)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12688\1598881097.py:1: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  adj_mat = nx.adjacency_matrix(g).toarray().astype(bool)


In [63]:
BR = np.random.rand(n_nodes, n_nodes)
FR = np.random.rand(n_nodes, n_nodes)

In [45]:
# BR = adj_mat.toarray() * BR

In [64]:
np.prod(BR, where=adj_mat, axis=1)

array([1.99511230e-01, 1.83449701e-01, 1.97763004e-02, 3.68251732e-02,
       2.86532827e-01, 4.04955553e-03, 2.88608667e-02, 3.49974728e-03,
       2.47775746e-10, 7.31565050e-04, 2.80841712e-05, 9.21800846e-03,
       1.45865735e-03, 1.31415191e-03, 1.54816396e-03, 2.75256693e-03,
       3.75839845e-04, 1.38036214e-04, 6.66060446e-02, 1.72695466e-02])

In [52]:
a = np.array([
    [1., 2.], 
    [3., 4.]
])

In [53]:
np.prod(a, axis=1)

array([ 2., 12.])

In [46]:
BR

array([[0.        , 0.        , 0.        , 0.8697425 , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.74216256,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.74674414, 0.        , 0.52563057, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.01180834, 0.95557868, 0.        ,
        0.        , 0.        , 0.        , 0.89510718, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.89620927, 0.        ,
        0.        , 0.        , 0.25183087, 0.        , 0.        ,
        0.        , 0.85911982, 0.        , 0.79353178, 0.90101406,
        0.        , 0.50635114, 0.        , 0.22770244, 0.        ],
       [0.08063699, 0.        , 0.874556  , 0.        , 0.        ,
        0.        , 0.        , 0.94121869, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0

In [ ]:
np.prod()

In [ ]:
nx.draw(g)

In [19]:
nx.set_node_attributes(g, {i:{"BR":np.random.rand()} for i in range(20)})
nx.set_node_attributes(g, {i:{"FR":np.random.rand()} for i in range(20)})